# This config file for Travis CI
sudo: required
dist: trusty
language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true
  submodules: false

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DTRAJOPT_ENABLE_TESTING=ON -DTRAJOPT_ENABLE_RUN_TESTING=OFF"
    - ROSDEP_SKIP_KEYS="bullet3 fcl"
    - BUILD_PKGS_WHITELIST="trajopt trajopt_sco trajopt_tools trajopt_utils trajopt_ifopt trajopt_sqp"
    - AFTER_SCRIPT='catkin test -w $CATKIN_WORKSPACE --no-deps trajopt trajopt_sco'
    - PKGS_DOWNSTREAM=''

matrix:
  include:
    - env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file CLANG_FORMAT_VERSION=8 AFTER_SCRIPT=""
    - env: ROS_DISTRO=kinetic DOCKER_IMAGE=lharmstrong/tesseract:kinetic ROSDEP_SKIP_KEYS="bullet3 fcl benchmark"
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:kinetic ROSDEP_SKIP_KEYS="bullet3 fcl benchmark"
    - env: ROS_DISTRO=melodic DOCKER_IMAGE=lharmstrong/tesseract:melodic ROS_PARALLEL_JOBS=-j4 ROS_PARALLEL_TEST_JOBS=-j4
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:melodic ROS_PARALLEL_JOBS=-j4 ROS_PARALLEL_TEST_JOBS=-j4
  allow_failures:
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:kinetic ROSDEP_SKIP_KEYS="bullet3 fcl benchmark"
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:melodic ROS_PARALLEL_JOBS=-j4 ROS_PARALLEL_TEST_JOBS=-j4

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
