<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find fanuc_resources)/urdf/common_materials.xacro"  />

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>
    <xacro:property name="base_radius" value="0.20"/>
    <xacro:property name="base_length" value="0.16"/>

    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_joint_y" value="0.19"/>
    <xacro:property name="wheel_joint_z" value="0.05"/>

    <xacro:property name="caster_radius" value="0.015"/> <!-- wheel_radius - ( base_length/2 - wheel_joint_z) -->
    <xacro:property name="caster_joint_x" value="0.18"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
  
    <!-- Macro for robot wheel -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster -->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(base_length/2 + caster_radius)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="mbot_base">
        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${base_length/2 + caster_radius*2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${base_length}" radius="${base_radius}"/>
                </geometry>
                <material name="yellow" />
            </visual>
        </link>

        <wheel prefix="left" reflect="-1"/>
        <wheel prefix="right" reflect="1"/>

        <caster prefix="front" reflect="-1"/>
        <caster prefix="back" reflect="1"/>
    </xacro:macro>

  

  <!-- old here-->
  <xacro:macro name="fanuc_r2000ic165f" params="prefix">
    <!-- links: main serial chain -->
    <link name="world" />
    <joint name="${prefix}world_base_link" type="fixed">
        <parent link="world" />
        <child link="${prefix}base_link" />
        <origin rpy="0 0 0" xyz="-2.5 0 0" />
    </joint>

    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/base_link.stl"/>
        </geometry>
        <xacro:material_fanuc_gray40 />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/base_link.stl"/>
        </geometry>
      </collision>

      <inertial>
               <mass value="10.0" />
               <origin rpy="0.002688 0.004043 0.006103" xyz="-0.064613 -0.005314 0.100271" />
               <inertia ixx="0.002695" ixy="0.000023" ixz="0.000157" iyy="0.004043" iyz="0.000023" izz="0.006096" />
      </inertial>


    </link>
    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_1.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_1.stl"/>
        </geometry>
      </collision>

      <inertial>
                <mass value="5.0" />
                <origin rpy="0.011358 0.019634 0.020073" xyz="0.010863 0.053239 0.523328" />
                <inertia ixx="0.012932" ixy="0.003309" ixz=" -0.000331" iyy="0.018366" iyz="-0.000071" izz="0.019767" />
      </inertial>

    </link>
    <link name="${prefix}link_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_2.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_2.stl"/>
        </geometry>
      </collision>

      <inertial>
                <mass value="4.0" />
                <origin rpy="0.001934 0.014381 0.015249" xyz="-0.001481 0.204359 0.436864" />
                <inertia ixx="0.014390" ixy="0.000091" ixz="-0.000323" iyy="0.015120" iyz="-0.001213" izz="0.002053" />
      </inertial>

    </link>
    <link name="${prefix}link_3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_3.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_3.stl"/>
        </geometry>
      </collision>

      <inertial>
               <mass value="4.0" />
               <origin rpy="0.000964 0.001451 0.001518" xyz="0.059293 0.012994 0.109078" />
               <inertia ixx="0.001451" ixy="0.000017" ixz="-0.000177" iyy="0.001441" iyz="0.000072" izz="0.001041" />
      </inertial>

    </link>
    <link name="${prefix}link_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_4.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_4.stl"/>
        </geometry>
      </collision>

      <inertial>
               <mass value="5.0" />
               <origin rpy="0.000333 0.004282 0.004287" xyz="0.711733 -0.002537 -0.000643" />
               <inertia ixx="0.000333" ixy="0.000044" ixz="0.000006" iyy="0.004287" iyz="-0.000000" izz="0.004282" />
      </inertial>

    </link>
    <link name="${prefix}link_5">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_5.stl"/>
        </geometry>
        <xacro:material_fanuc_yellow />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_5.stl"/>
        </geometry>
      </collision>

      <inertial>
                <mass value="8.0" />
                <origin rpy="0.000078 0.000103 0.000118" xyz="0.042035 -0.024095 -0.001620" />
                <inertia ixx="0.000088" ixy="-0.000012" ixz="0.000000" iyy="0.000094" iyz="0.000000" izz="0.000118" />
      </inertial>

    </link>
    <link name="${prefix}link_6">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/link_6.stl"/>
        </geometry>
        <xacro:material_fanuc_black />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/link_6.stl"/>
        </geometry>
      </collision>

      <inertial>
                <mass value="5.0" />
                <origin rpy="0.000001 0.000001 0.000002" xyz="-0.018677 -0.000000 -0.000002" />
                <inertia ixx="0.000002" ixy="0.000000" ixz="-0.000000" iyy="0.000001" iyz="0.000000" izz="0.000001" />
      </inertial>

    </link>
    <link name="${prefix}ef">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/visual/ef.stl"/>
            </geometry>
            <xacro:material_fanuc_yellow />
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://fanuc_r2000ic_support/meshes/r2000ic165f/collision/ef.stl"/>
            </geometry>
          </collision>

          <inertial>
                       <mass value="3.0" />
                       <origin rpy="0.000082 0.000185 0.000195" xyz="0.0 0.0 0.0" />
                       <inertia ixx="0.000127" ixy="0.000000" ixz="0.000052" iyy="0.000194" iyz="0.000003" izz="0.000141" />
           </inertial>

        </link>

    <!--mbot_base -->

    <link name="agv_base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.16" radius="0.20"/>
            </geometry>
            <material name="yellow">
                <color rgba="1 0.4 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="agv_base_link" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="agv_base_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 0.19 -0.05" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.9"/>
            </material>
        </visual>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 -0.19 -0.05" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.5707 0 0" />
            <geometry>
                <cylinder radius="0.06" length = "0.025"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.9"/>
            </material>
        </visual>
    </link>

    <joint name="front_caster_joint" type="continuous">
        <origin xyz="0.18 0 -0.095" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_caster_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_caster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.015" />
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.95"/>
            </material>
        </visual>
    </link>

    <joint name="back_caster_joint" type="continuous">
        <origin xyz="-0.18 0 -0.095" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_caster_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="back_caster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.015" />
            </geometry>
            <material name="black">
                <color rgba="0 0 0 0.95"/>
            </material>
        </visual>
    </link>

    <!-- joints: main serial chain -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-185)}" upper="${radians(185)}" effort="0" velocity="${radians(130)}"/>
    </joint>
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0.312 0 0.670" rpy="0 0 0"/>
      <parent link="${prefix}link_1"/>
      <child link="${prefix}link_2"/>
      <axis xyz="0 1 0"/>
      <limit lower="${radians(-60)}" upper="${radians(76)}" effort="0" velocity="${radians(115)}"/>
    </joint>
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="0 0 1.075" rpy="0 0 0"/>
      <parent link="${prefix}link_2"/>
      <child link="${prefix}link_3"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${radians(-132)}" upper="${radians(180)}" effort="0" velocity="${radians(125)}"/>
    </joint>
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="0 0 0.225" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="-1 0 0"/>
      <limit lower="${radians(-360)}" upper="${radians(360)}" effort="0" velocity="${radians(180)}"/>
    </joint>
    <joint name="${prefix}joint_5" type="revolute">
      <origin xyz="1.280 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}link_5"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${radians(-125)}" upper="${radians(125)}" effort="0" velocity="${radians(180)}"/>
    </joint>
    <joint name="${prefix}joint_6" type="revolute">
      <origin xyz="0.215 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_5"/>
      <child link="${prefix}link_6"/>
      <axis xyz="-1 0 0"/>
      <limit lower="${radians(-360)}" upper="${radians(360)}" effort="0" velocity="${radians(260)}"/>
    </joint>



    <!-- ROS-Industrial 'base' frame: base_link to Fanuc World Coordinates transform -->
    <link name="${prefix}base" />
    <joint name="${prefix}base_link-base" type="fixed">
      <origin xyz="0 0 0.670" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
    <link name="${prefix}flange" />
    <joint name="${prefix}joint_6-flange" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}flange" />
    </joint>

    <!-- ROS-Industrial 'tool0' frame: all-zeros tool frame -->
    <link name="${prefix}tool0" />
    <joint name="${prefix}flange-tool0" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${radians(90)} 0" />
      <parent link="${prefix}link_6" />
      <child link="${prefix}tool0" />
    </joint>
    <joint name="${prefix}flange-ef" type="fixed">
          <origin xyz="0 0 0" rpy="${radians(180)} ${radians(-180)} 0" />
          <parent link="${prefix}tool0" />
          <child link="${prefix}ef" />
        </joint>
    <link name="${prefix}tcp" />
    <joint name="${prefix}tcp_ef" type="fixed">
       <origin xyz="-0.204433413 -7.32E-04 0.333181177" rpy="5.53832e-13 -0.785398 0"/>
      <parent link="${prefix}ef" />
      <child link="${prefix}tcp" />
    </joint>


    <link name="${prefix}gazebo_camera_link" >

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <box size="0.1 0.1 0.1"/>
      </geometry>
      <xacro:material_fanuc_yellow />
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

    </link>
    <joint name="${prefix}gazebo_camera_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="1.57 -1.57 0"/>
        <parent link="${prefix}camera_link_optical"/>
        <child link="${prefix}gazebo_camera_link"/>
    </joint>
    <link name="${prefix}camera_link_optical">

    </link>
    <joint name="${prefix}camera_optical_joint" type="fixed">
        <origin xyz="0.1 0 0.2" rpy="0 0 0"/>
        <parent link="${prefix}ef"/>
        <child link="${prefix}camera_link_optical"/>
    </joint>
    <link name="${prefix}camera_link" />
    <joint name="${prefix}camera_link_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="1.57 -1.57 0"/>
        <parent link="${prefix}camera_link_optical"/>
        <child link="${prefix}camera_link"/>
    </joint>




    <transmission name="trans_joint_1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}joint_1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_1_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

<transmission name="trans_joint_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}joint_2">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_2_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="trans_joint_3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}joint_3">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_3_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="trans_joint_4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}joint_4">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_4_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="trans_joint_5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}joint_5">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_5_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="trans_joint_6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${prefix}joint_6">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_6_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>



    <gazebo reference="${prefix}base_link">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_1">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_2">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_3">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_4">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_5">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}link_6">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="${prefix}ef">
        <selfCollide>true</selfCollide>
    </gazebo>

    <gazebo reference="${prefix}tool0">
        <selfCollide>true</selfCollide>
    </gazebo>


    <gazebo reference="${prefix}flange">
        <selfCollide>true</selfCollide>
    </gazebo>


<gazebo reference="${prefix}gazebo_camera_link">
        <sensor type="depth" name="sensor_name">
          <!-- Set always_on only sensor, not on plugin -->
          <always_on>1</always_on>
          <!-- Set update_rate only sensor, not on plugin -->
          <update_rate>5</update_rate>
          <camera name="camera_name">
            <image>
              <width>320</width>
              <height>200</height>
            </image>
            <distortion>
              <k1>-0.0</k1>
              <k2>0.0</k2>
              <k3>0.0</k3>
              <p1>-0.0</p1>
              <p2>-0.0</p2>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
          <plugin name="plugin_name" filename="libgazebo_ros_camera.so">
            <!-- Change namespace, camera name and topics so:
                 * Raw images are published to: /custom_ns/custom_camera/custom_image
                 * Depth images are published to: /custom_ns/custom_camera/custom_image_depth
                 * Raw image camera info is published to: /custom_ns/custom_camera/custom_info_raw
                 * Depth image camera info is published to: /custom_ns/custom_camera/custom_info_depth
                 * Point cloud is published to: /custom_ns/custom_camera/custom_points
            -->
            <ros>
              <namespace>custom_ns</namespace>
              <argument>camera/image_raw:=camera/custom_image</argument>
              <argument>camera/image_depth:=camera/custom_image_depth</argument>
              <argument>camera/camera_info:=camera/custom_info_raw</argument>
              <argument>camera/camera_info_depth:=camera/custom_info_depth</argument>
              <argument>camera/points:=camera/pointcloud</argument>
            </ros>
            <!-- Set camera name. If empty, defaults to sensor name (i.e. "sensor_name") -->
            <camera_name>camera</camera_name>
            <frame_name>camera_link_optical</frame_name>
            <!-- Set TF frame name. If empty, defaults to link name (i.e. "link_name") -->
            <hack_baseline>0.07</hack_baseline>
            <!-- No need to repeat distortion parameters or to set autoDistortion -->
             <min_depth>0.1</min_depth>
          </plugin>
        </sensor>
    </gazebo>

    <gazebo>

        <plugin name='gazebo_ros_joint_state_publisher' filename='libgazebo_ros_joint_state_publisher.so'>
          <ros>
              <namespace>/test</namespace>
              <argument>joint_states:=joint_states</argument>
          </ros>
          <update_rate>50</update_rate>

          <joint_name>${prefix}joint_1</joint_name>
          <joint_name>${prefix}joint_2</joint_name>
          <joint_name>${prefix}joint_3</joint_name>
          <joint_name>${prefix}joint_4</joint_name>
          <joint_name>${prefix}joint_5</joint_name>
          <joint_name>${prefix}joint_6</joint_name>

        </plugin>

        <plugin name='crs_gazebo_plugins_joint_pose_trajectory' filename='libcrs_gazebo_plugins_joint_pose_trajectory.so'>
            <ros>
              <namespace>sim</namespace>
              <argument>follow_joint_trajectory:=${prefix}follow_joint_trajectory</argument>
            </ros>
            <update_rate>20</update_rate>
        </plugin>
    </gazebo>


  </xacro:macro>
</robot>
