general:
  use_trajopt_freespace: false
  use_trajopt_surface: false
  default_to_descartes: true
  default_to_ompl: true
  simplify_start_end_freespace: true
  manipulator: "manipulator"
  world_frame: "world"
  robot_base_frame: "base_link"
  tool0_frame: "ef"
  required_tool_vel: false
  max_joint_vel: 1.0 #0.3
  max_joint_vel_mult: 50 #1.80
  max_surface_dist: 0.5 #0.15
  max_rotation_rate: 50 #3.0
  max_joint_acc: 100 #0.8
  add_approach_and_retreat: true
  minimum_raster_length: 0
  reachable_radius: 1.35
  trajopt_verbose_output: false
  combine_strips: true
  global_descartes: true
descartes:
  axial_step: 0.9
  collision_safety_margin: 0.00
  additional_tool_offset: [0.0, 0.0, 0.004, 0.0, 0.0, 0.0]
  joint_min_vals: [-0.1, -0.1, -0.4, -0.1, 0.1, -0.1]
trajopt_surface:
  smooth_velocities: true
  smooth_accelerations: true
  smooth_jerks: false
  longest_valid_segment_fraction: 1.0
  longest_valid_segment_length: 1.0
  surface_coefficients: [10.0, 10.0, 10.0, 10.0, 10.0, 0.0]
  waypoints_critical: true
  collision_cost:
    enabled: false
    buffer_margin: 0.03
  special_collision_costs:
    - link1: "robot_stand"
      link2: "upper_arm_link"
      distance: 0.03
      cost: 10.0
  collision_constraint:
    enabled: false
    safety_margin: 0.000
  special_collision_constraints:
    - link1: "eoat_link"
      link2: "part_link"
      distance: -0.05
      cost: 10.0
ompl:
  collision_safety_margin: 0.00
  planning_time: 240.0
  simplify: true
  range: 0.15
  num_threads: 8
  max_solutions: 10
  default_n_output_states: 20
  longest_valid_segment_fraction: 0.05
  longest_valid_segment_length: 0.5
  retry_failure: true
  retry_distance: 0.2
  retry_at_zero: true
trajopt_freespace:
  smooth_velocities: true
  smooth_accelerations: true
  smooth_jerks: true
  longest_valid_segment_fraction: 0.01
  longest_valid_segment_length: 0.5
  collision_cost:
    enabled: false
    buffer_margin: 0.02
  special_collision_costs:
    - link1: "eoat_link"
      link2: "part_link"
      distance: 0.05
      cost: 10.0
  collision_constraint:
    enabled: false
    safety_margin: 0.005
